import type { JourneyNode } from "@/components/journey/JourneyMap"

export const ECG_JOURNEY: JourneyNode[] = [
  {
    id: "ecg-1",
    title: "Lead Layout",
    subtitle: "Anchor the 12-lead mental map.",
    href: "/ecg/practice",
    type: "skill",
    xp: 20,
    state: "done",
  },
  {
    id: "ecg-2",
    title: "Rate Sprint",
    subtitle: "Rapid rhythm and rate checks.",
    href: "/ecg/practice",
    type: "practice",
    xp: 25,
    state: "done",
  },
  {
    id: "ecg-3",
    title: "Axis Detective",
    subtitle: "Nail axis calls under pressure.",
    href: "/ecg/practice",
    type: "checkpoint",
    xp: 30,
    state: "next",
  },
  {
    id: "ecg-4",
    title: "Case Round I",
    subtitle: "Bradycardia vs AV block.",
    href: "/ecg/cases",
    type: "case",
    xp: 35,
    pro: true,
    state: "next",
  },
  {
    id: "ecg-5",
    title: "Interval Lab",
    subtitle: "PR, QRS, QT mastery loop.",
    href: "/ecg/practice",
    type: "practice",
    xp: 40,
    state: "current",
  },
  {
    id: "ecg-6",
    title: "Morphology Match",
    subtitle: "Pattern spotting for ischemia.",
    href: "/ecg/practice",
    type: "skill",
    xp: 45,
    state: "next",
  },
  {
    id: "ecg-7",
    title: "Case Round II",
    subtitle: "ACS and STEMI mimic drill.",
    href: "/ecg/cases",
    type: "case",
    xp: 50,
    pro: true,
    state: "next",
  },
  {
    id: "ecg-8",
    title: "Arrhythmia Boss",
    subtitle: "Mixed tachycardia gauntlet.",
    href: "/ecg/practice",
    type: "boss",
    xp: 60,
    state: "next",
  },
]

export const XRAY_JOURNEY: JourneyNode[] = [
  {
    id: "xray-1",
    title: "View Check",
    subtitle: "PA vs AP recognition warmup.",
    href: "/xray/practice",
    type: "skill",
    xp: 20,
    state: "done",
  },
  {
    id: "xray-2",
    title: "Anatomy Sweep",
    subtitle: "Read lungs, heart, pleura in order.",
    href: "/xray/practice",
    type: "practice",
    xp: 25,
    state: "done",
  },
  {
    id: "xray-3",
    title: "Opacity Hunt",
    subtitle: "Consolidation and edema patterns.",
    href: "/xray/practice",
    type: "checkpoint",
    xp: 30,
    state: "next",
  },
  {
    id: "xray-4",
    title: "Case Round I",
    subtitle: "Pneumonia localization drill.",
    href: "/xray/cases",
    type: "case",
    xp: 35,
    pro: true,
    state: "next",
  },
  {
    id: "xray-5",
    title: "Pleural Focus",
    subtitle: "Effusion and pneumothorax cues.",
    href: "/xray/practice",
    type: "practice",
    xp: 40,
    state: "current",
  },
  {
    id: "xray-6",
    title: "Cardiac Silhouette",
    subtitle: "Cardiomegaly and projection bias.",
    href: "/xray/practice",
    type: "skill",
    xp: 45,
    state: "next",
  },
  {
    id: "xray-7",
    title: "Case Round II",
    subtitle: "Mixed pathology differential.",
    href: "/xray/cases",
    type: "case",
    xp: 50,
    pro: true,
    state: "next",
  },
  {
    id: "xray-8",
    title: "Portable Boss",
    subtitle: "Noisy AP films under time pressure.",
    href: "/xray/practice",
    type: "boss",
    xp: 60,
    state: "next",
  },
]
