import Link from "next/link"
import { BookOpen, CalendarDays, CircleHelp, Clock3, Mail, MessageSquareText, UserRoundCheck } from "lucide-react"

import { getEnterpriseWorkspace, getGrowthWorkspace, requireStarterPortalContext } from "@/server/institution"

export default async function InstitutionSupportPage() {
  const { context } = await requireStarterPortalContext("/institution/support")
  const [growth, enterprise] = await Promise.all([getGrowthWorkspace(context), getEnterpriseWorkspace(context)])
  const subject = encodeURIComponent(`MedLab support · ${context.institution.name}`)
  return (
    <main>
      <header className="institution-page-header"><div><p className="institution-eyebrow">{growth.plan.charAt(0) + growth.plan.slice(1).toLowerCase()} support</p><h1 className="institution-title">How can we help?</h1><p className="institution-subtitle">Email support is included in every institutional plan. Include the class and affected user when reporting an access or data issue.</p></div></header>
      {growth.hasGrowth ? <section className="mb-5 grid gap-5 md:grid-cols-2"><article className="institution-panel p-5"><UserRoundCheck className="h-5 w-5 text-[#0066ff]" /><h2 className="mt-4 text-base font-semibold text-[#0e0f12]">Dedicated account manager</h2>{growth.successProfile?.accountManagerName ? <><p className="mt-2 text-sm font-semibold text-[#353431]">{growth.successProfile.accountManagerName}</p><p className="mt-1 text-xs text-[#8a8881]">Your point of contact for rollout, adoption, and outcomes.</p><div className="mt-5 flex flex-wrap gap-2">{growth.successProfile.accountManagerEmail ? <a href={`mailto:${growth.successProfile.accountManagerEmail}`} className="institution-button-primary">Email manager</a> : null}{growth.successProfile.accountManagerCalendarUrl ? <a href={growth.successProfile.accountManagerCalendarUrl} target="_blank" rel="noreferrer" className="institution-button-secondary">Book a call</a> : null}</div></> : <p className="mt-2 text-sm leading-6 text-[#6b6a65]">Your named account manager is being assigned.</p>}</article><article className="institution-panel p-5"><CalendarDays className="h-5 w-5 text-[#0066ff]" /><h2 className="mt-4 text-base font-semibold text-[#0e0f12]">Quarterly review</h2><p className="mt-2 text-sm leading-6 text-[#6b6a65]">Review adoption, assignment completion, weak-case trends, and your next rollout priorities.</p><p className="mt-4 rounded-[9px] bg-[#f5f3ed] px-3.5 py-3 text-xs font-semibold text-[#4f4d47]">{growth.successProfile?.nextReviewAt ? `Next review · ${new Date(growth.successProfile.nextReviewAt).toLocaleString()}` : "Next review date is being coordinated"}</p></article></section> : null}
      {enterprise.hasEnterprise && !enterprise.setupRequired ? <section className="institution-panel mb-5 flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="rounded-[10px] bg-[var(--institution-accent)] p-2.5"><Clock3 className="h-5 w-5 text-[var(--institution-primary)]" /></div><div><h2 className="text-base font-semibold text-[#0e0f12]">Enterprise priority support</h2><p className="mt-1 text-sm text-[#6b6a65]">{enterprise.prioritySupport?.responseMinutes ? `Contracted first-response target: ${enterprise.prioritySupport.responseMinutes} minutes.` : "Your contracted response target is being configured."}</p></div></div>{enterprise.prioritySupport?.email ? <a href={`mailto:${enterprise.prioritySupport.email}?subject=${subject}`} className="institution-button-primary">Contact priority support</a> : null}</section> : null}
      <section className="grid gap-5 md:grid-cols-3">
        <article className="institution-panel p-5"><Mail className="h-5 w-5 text-[#0066ff]" /><h2 className="mt-4 text-base font-semibold text-[#0e0f12]">Email support</h2><p className="mt-2 text-sm leading-6 text-[#6b6a65]">Contact the MedLab team for product, access, or reporting questions.</p><a href={`mailto:support@getmedlab.com?subject=${subject}`} className="institution-button-primary mt-6 w-full">Email support</a></article>
        <article className="institution-panel p-5"><CircleHelp className="h-5 w-5 text-[#0066ff]" /><h2 className="mt-4 text-base font-semibold text-[#0e0f12]">Common tasks</h2><div className="mt-4 space-y-2"><Link href="/institution/educators" className="block rounded-[9px] bg-[#f5f3ed] px-3 py-2.5 text-xs font-semibold text-[#4f4d47]">Invite an educator</Link><Link href="/institution/students" className="block rounded-[9px] bg-[#f5f3ed] px-3 py-2.5 text-xs font-semibold text-[#4f4d47]">Import or assign students</Link><Link href="/institution/reports" className="block rounded-[9px] bg-[#f5f3ed] px-3 py-2.5 text-xs font-semibold text-[#4f4d47]">Export performance</Link></div></article>
        <article className="institution-panel p-5"><MessageSquareText className="h-5 w-5 text-[#0066ff]" /><h2 className="mt-4 text-base font-semibold text-[#0e0f12]">What to include</h2><ul className="mt-4 space-y-2 text-xs leading-5 text-[#6b6a65]"><li>• Institution and class name</li><li>• User email, when relevant</li><li>• What you expected to happen</li><li>• Screenshot or exact error message</li></ul><div className="mt-5 flex items-center gap-2 text-[11px] font-semibold text-[#77746d]"><BookOpen className="h-3.5 w-3.5" /> Response handled by email</div></article>
      </section>
    </main>
  )
}
