import { Figtree } from "next/font/google";
import "./globals.css";

// Configure the font
const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Select the weights you need
  variable: "--font-figtree", // Optional: Create a CSS variable
});

export const metadata = {
  title: "MedLab",
  description: "Generated by create next app",
};

// apps/student/app/layout.tsx
import "./globals.css"
import { AuthProvider } from "@/contexts/AuthContext"
import { GatingProvider } from "@/contexts/GatingContext"
import { Toaster } from "sonner"

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={figtree.className}>
        <AuthProvider>
          <GatingProvider>
            {children}
            <Toaster richColors position="top-center" />
          </GatingProvider>
        </AuthProvider>
      </body>
    </html>
  )
}